### ISSUE TITLE
Missing pull-up resistor on RST on Lora Shield

### ISSUE THREAD

**Issue by cc32d9** [dragino/Lora#13]
see details at https://github.com/manuelbl/ttn-esp32/issues/23

the RST pin on the LoRa shield is missing a pull-up, so the chip is not working if RST pin stops driving.

**Comment by cc32d9** [comment]
more details: https://github.com/mcci-catena/arduino-lmic/issues/579

**Comment by dragino** [comment]
Thanks. We will fixed this in the next production.
